name: Go Contract Image CI

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
    paths:
      - 'samples/go-contract/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'samples/go-contract/**'

permissions: read-all

jobs:
  docker_build:
    name: Docker build
    permissions:
      contents: write
      packages: write
      id-token: write
    uses: ./.github/workflows/docker-build.yml
    with:
      platforms: linux/amd64,linux/arm64
      image-name: ghcr.io/hyperledger-labs/fabric-builder-k8s/sample-go-contract
      path: samples/go-contract
      chaincode-label: go-contract
