name: Go Contract Image CI

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
    paths:
      - 'samples/go-contract/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'samples/go-contract/**'

jobs:
  docker_build:
    name: Docker build
    uses: ./.github/workflows/docker-build.yml
    with:
      imagename: go-contract
      path: samples/go-contract
      chaincode: true
