name: golangci-lint

on:
  push:
    branches: [ main ]
    tags: [ v** ]
    paths-ignore:
      - '*.md'
      - 'mkdocs.yml'
      - 'requirements.txt'
      - 'docs/**'
      - 'samples/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - 'mkdocs.yml'
      - 'requirements.txt'
      - 'docs/**'
      - 'samples/**'

permissions: read-all

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: 1.26
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.12.2
