name: Skip status checks

on:
  pull_request:
    paths:
      - '*.md'
      - 'docs/**'
      - 'samples/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No lint required"'

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        goarch: [amd64]
    steps:
      - run: 'echo "No build required"'

  docker_build:
    name: Docker build
    uses: ./.github/workflows/status-checks-docker.yml
